// atomic-react/src/components/pages/OverviewPage.tsx
import OverviewContent from "../organisms/OverviewContent";
import OverviewNavigation from "../organisms/OverviewNavigation";
import OverviewTemplate, {
  OverviewTemplateProps,
} from "../templates/OverviewTemplate";

const OverviewPage = () => {
  const templateProps: OverviewTemplateProps = {
    navigation: <OverviewNavigation />,
    content: <OverviewContent />,
  };
  return <OverviewTemplate {...templateProps} />;
};

export default OverviewPage;

// atomic-vue/src/components/pages/OverviewPage.vue
<template>
  <OverviewTemplate>
    <template v-slot:navbar><OverviewNavigation /></template>
    <template v-slot:content><router-view></router-view></template>
  </OverviewTemplate>
</template>

<script>
import OverviewTemplate from "@templates/OverviewTemplate.vue";
import OverviewNavigation from "@organisms/OverviewNavigation.vue";

export default {
  name: "OverviewPage",
  components: { OverviewTemplate, OverviewNavigation },
};
</script>

<style></style>
